steps:
  - name: 'gcr.io/open-search-345216/helm'
    args: ['repo', 'add', 'opensearch', 'https://opensearch-project.github.io/helm-charts/']
  - name: 'gcr.io/open-search-345216/helm'
    args: ['repo', 'update']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - cluster-info
    env:
      - KUBECONFIG=/workspace/.kube/config
  - name: 'gcr.io/open-search-345216/helm'
    args: ['upgrade', 'opensearch-data', 'opensearch/opensearch', '-f', 'data.yaml']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -exc
      - |  
        apt-get update
        apt-get install jq -y
        ./vm_fix_file.sh
options:
  logging: CLOUD_LOGGING_ONLY
  env:
      - CLOUDSDK_COMPUTE_REGION=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=cluster-2
      - GCLOUD_PROJECT=open-search-345216