steps:
  - name: 'gcr.io/open-search-345216/helm'
    args: ['repo', 'add', 'opensearch', 'https://opensearch-project.github.io/helm-charts/']
  - name: 'gcr.io/open-search-345216/helm'
    args: ['repo', 'update']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - cluster-info
    env:
      - KUBECONFIG=/workspace/.kube/config
  - name: 'gcr.io/open-search-345216/helm'
    args: ['upgrade', 'opensearch-data', 'opensearch/opensearch', '-f', 'data.yaml']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gsutil', 'cp', '-r', 'gs://artifacts.<PROJECT-ID>.appspot.com/.ssh', '/builder/home/']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args: ['-c', 'chmod 400 /builder/home/.ssh/build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'compute', 'ssh', '--zone=<ZONE>', 'build@<INSTANCE-ID>', '--ssh-key-file=/builder/home/.ssh/build', '--', 'ls -al']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -exc
      - |  
        apt-get update
        apt-get install jq -y
        bash vm_fix_file.sh
options:
  logging: CLOUD_LOGGING_ONLY
  env:
      - CLOUDSDK_COMPUTE_REGION=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=cluster-2
      - GCLOUD_PROJECT=open-search-345216