apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: opensearch.k8s.local
  name: data-nodes-us-east-1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220509
  machineType: i3.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: data-nodes-us-east-1
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1d